# Generated by Django 3.2.8 on 2023-03-24 23:38

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.Profile.get_upload_folder, verbose_name='аватарка')),
                ('coffee_count', models.IntegerField(default=0, verbose_name='кофе')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'дополнительная информация',
            },
        ),
    ]
