# Generated by Django 3.2.8 on 2023-03-24 12:21

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'дополнительная информация'},
        ),
    ]
