# Generated by Django 3.2.8 on 2023-03-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('received', 'получено'), ('idle', 'в процессе'), ('answered', 'ответ дан')], default='received', max_length=16),
        ),
    ]
