# Generated by Django 3.2.8 on 2023-03-19 15:29

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20230315_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'вложение', 'verbose_name_plural': 'вложения'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратные связи'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=feedback.models.Attachment.get_upload_folder, verbose_name='вложение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('received', 'получено'), ('idle', 'в процессе'), ('answered', 'ответ дан')], default='received', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
