# Generated by Django 3.2.8 on 2023-02-19 13:54

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, validators=[catalog.validators.contains_perfect_words])),
                ('text', models.TextField()),
            ],
        ),
    ]
