# Generated by Django 3.2.8 on 2023-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogItem',
            new_name='Item',
        ),
    ]
