# Generated by Django 3.2.8 on 2023-03-07 15:09

import catalog.validators
from django.db import migrations, models
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230228_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='catalog/', verbose_name='прикрепите изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='catalog/', verbose_name='прикрепите изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='описание'),
        ),
    ]
