# Generated by Django 3.2.8 on 2023-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230223_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Нормальзованное имя'),
        ),
    ]
