# Generated by Django 3.2.8 on 2023-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tag_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Нормальзованное имя'),
        ),
        migrations.AddField(
            model_name='item',
            name='normalized_name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Нормальзованное имя'),
        ),
    ]
