# Generated by Django 3.2.8 on 2023-02-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230219_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='tag',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.item'),
        ),
    ]
