# Generated by Django 3.2.8 on 2023-03-10 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230307_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 10, 6, 55, 16, 800379, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='на главной странице'),
        ),
    ]
