# Generated by Django 3.2.8 on 2023-02-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20230228_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item'),
        ),
    ]
